<?php

namespace Database\Seeders;

use App\Models\Tumbuhan;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TumbuhanSeeder extends Seeder
{
    public function run()
    {
        // Data yang akan dimasukkan ke dalam tabel tumbuhans
        $data = [
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.736807',
                'longitude' => '107.005575',
                'nama' => 'Ramo giling',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.736807',
                'longitude' => '107.005575',
                'nama' => 'Daun paku/kijanggot',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.736807',
                'longitude' => '107.005575',
                'nama' => 'Rumput lancuran',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.736807',
                'longitude' => '107.005575',
                'nama' => 'Gandasoli',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.736807',
                'longitude' => '107.005575',
                'nama' => 'Hariang',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.736807',
                'longitude' => '107.005575',
                'nama' => 'Bungbrun merah',
            ],
            [
                'resort' => 'Tegallega',
                'bulan' => 'Januari',
                'latitude' => '-6.8233601',
                'longitude' => '107.0391393',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.737059',
                'longitude' => '107.003855',
                'nama' => 'Bunga sarundung/jujugan',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.737059',
                'longitude' => '107.003855',
                'nama' => 'Antimon tikus',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.737059',
                'longitude' => '107.003855',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.737059',
                'longitude' => '107.003855',
                'nama' => 'Daun paku/kijanggot',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.737059',
                'longitude' => '107.003855',
                'nama' => 'Acung',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Januari',
                'latitude' => '-6.737059',
                'longitude' => '107.003855',
                'nama' => 'Kalayar',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Januari',
                'latitude' => '-6.758388',
                'longitude' => '106.984062',
                'nama' => 'Harendong',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Januari',
                'latitude' => '-6.817573',
                'longitude' => '106.838392',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Januari',
                'latitude' => '-6.822648',
                'longitude' => '106.845014',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Januari',
                'latitude' => '-6.829342',
                'longitude' => '106.872037',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Januari',
                'latitude' => '-6.838373',
                'longitude' => '106.987978',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Januari',
                'latitude' => '-6.836343',
                'longitude' => '106.989187',
                'nama' => 'Akar kupu-kupu, rane',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Januari',
                'latitude' => '-6.837774',
                'longitude' => '106.984799',
                'nama' => 'Cangkoreh',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Januari',
                'latitude' => '-6.830826',
                'longitude' => '106.97248',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Januari',
                'latitude' => '-6.787278',
                'longitude' => '106.992334',
                'nama' => 'Sembung alangu/edelwis jawa',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Januari',
                'latitude' => '-6.786955',
                'longitude' => '106.993035',
                'nama' => 'Cantigi',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Januari',
                'latitude' => '-6.787015',
                'longitude' => '106.993018',
                'nama' => 'Cantigi wungu',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Januari',
                'latitude' => '-6.767694',
                'longitude' => '107.014399',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Januari',
                'latitude' => '-6.71361',
                'longitude' => '106.894476',
                'nama' => 'Kanikir',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Februari',
                'latitude' => '-6.776207',
                'longitude' => '107.017879',
                'nama' => 'Rotan ragas/hoe leuleus/bogo',
            ],
            [
                'resort' => 'Bodogol',
                'bulan' => 'Februari',
                'latitude' => '-6.78226',
                'longitude' => '106.829364',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Februari',
                'latitude' => '-6.730204',
                'longitude' => '106.941744',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Januari',
                'latitude' => '-6.729792',
                'longitude' => '106.941539',
                'nama' => 'Walen',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Februari',
                'latitude' => '-6.729144',
                'longitude' => '106.940664',
                'nama' => 'Kicareuh',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Februari',
                'latitude' => '-6.728258',
                'longitude' => '106.939076',
                'nama' => 'Huru cempaka',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Februari',
                'latitude' => '-6.727323',
                'longitude' => '106.938596',
                'nama' => 'Kicareuh',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Februari',
                'latitude' => '-6.725994',
                'longitude' => '106.927713',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Februari',
                'latitude' => '-6.823093',
                'longitude' => '106.833096',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Februari',
                'latitude' => '-6.826767',
                'longitude' => '106.849373',
                'nama' => 'Cangkoreh',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Februari',
                'latitude' => '-6.821173',
                'longitude' => '106.821013',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Februari',
                'latitude' => '-6.751158',
                'longitude' => '106.988578',
                'nama' => 'Kihujan',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Februari',
                'latitude' => '-6.767972',
                'longitude' => '107.0008',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Februari',
                'latitude' => '-6.730311',
                'longitude' => '106.997289',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Februari',
                'latitude' => '-6.735529',
                'longitude' => '106.912483',
                'nama' => 'Rotan badak/bungbuay',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Februari',
                'latitude' => '-6.74039',
                'longitude' => '106.916717',
                'nama' => 'Kilemo',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Februari',
                'latitude' => '-6.740871',
                'longitude' => '106.915039',
                'nama' => 'Riung anak',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Februari',
                'latitude' => '-6.835231',
                'longitude' => '106.969783',
                'nama' => 'Bingbin',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Maret',
                'latitude' => '-6.713578',
                'longitude' => '106.993102',
                'nama' => 'Kilemo',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Maret',
                'latitude' => '-6.76787',
                'longitude' => '107.013611',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Maret',
                'latitude' => '-6.730501',
                'longitude' => '106.99664',
                'nama' => 'Riung anak',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Maret',
                'latitude' => '-6.730501',
                'longitude' => '106.99664',
                'nama' => 'Antanan gunung',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Maret',
                'latitude' => '-6.836323',
                'longitude' => '106.954789',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Maret',
                'latitude' => '-6.829701',
                'longitude' => '106.840017',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Maret',
                'latitude' => '-6.825595',
                'longitude' => '106.834546',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Maret',
                'latitude' => '-6.82555',
                'longitude' => '106.841861',
                'nama' => 'Pulus jalatrong',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'April',
                'latitude' => '-6.75259',
                'longitude' => '106.98683',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'April',
                'latitude' => '-6.735446',
                'longitude' => '107.005518',
                'nama' => 'Antanan gunung',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'April',
                'latitude' => '-6.826387',
                'longitude' => '106.833022',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'April',
                'latitude' => '-6.82789',
                'longitude' => '106.833696',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'April',
                'latitude' => '-6.824371',
                'longitude' => '106.825523',
                'nama' => 'Reundeu bulu',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'April',
                'latitude' => '-6.838092',
                'longitude' => '106.961318',
                'nama' => 'Bingbin',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'April',
                'latitude' => '-6.756902',
                'longitude' => '107.001666',
                'nama' => 'Jamuju',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'April',
                'latitude' => '-6.840215',
                'longitude' => '106.987317',
                'nama' => 'Akar kupu-kupu, rane',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'April',
                'latitude' => '-6.841376',
                'longitude' => '106.9848',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Maret',
                'latitude' => '-6.79259',
                'longitude' => '107.041638',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Maret',
                'latitude' => '-6.792591',
                'longitude' => '107.041638',
                'nama' => 'Jamuju',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'April',
                'latitude' => '-6.790885',
                'longitude' => '107.043637',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'April',
                'latitude' => '-6.790885',
                'longitude' => '107.043637',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Maret',
                'latitude' => '-6.707032',
                'longitude' => '106.885067',
                'nama' => 'Awi bitung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Maret',
                'latitude' => '-6.712985',
                'longitude' => '106.889124',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Maret',
                'latitude' => '-6.708501',
                'longitude' => '106.90936',
                'nama' => 'Alang-alang, jukut eurih',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Maret',
                'latitude' => '-6.711745',
                'longitude' => '106.911335',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Maret',
                'latitude' => '-6.715912',
                'longitude' => '106.913265',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'April',
                'latitude' => '-6.711141',
                'longitude' => '106.9077176',
                'nama' => 'Awi tali',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'April',
                'latitude' => '-6.715644',
                'longitude' => '106.910286',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'April',
                'latitude' => '-6.718017',
                'longitude' => '106.911126',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Januari',
                'latitude' => '-6.819521',
                'longitude' => '106.898969',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Januari',
                'latitude' => '-6.825312',
                'longitude' => '106.915756',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Februari',
                'latitude' => '-6.814501',
                'longitude' => '106.914811',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Februari',
                'latitude' => '-6.802946',
                'longitude' => '106.91221',
                'nama' => 'Kihujan',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'April',
                'latitude' => '-6.829813',
                'longitude' => '106.889082',
                'nama' => 'Reundeu',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'April',
                'latitude' => '-6.818711',
                'longitude' => '106.909088',
                'nama' => 'Hareueus',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'April',
                'latitude' => '-6.831434',
                'longitude' => '106.9244527',
                'nama' => 'Cangkoreh',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Maret',
                'latitude' => '-6.832673',
                'longitude' => '106.910157',
                'nama' => 'Rotan badak/bungbuay',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Mei',
                'latitude' => '-6.83705',
                'longitude' => '106.92665',
                'nama' => 'Kareumbi',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Mei',
                'latitude' => '-6.83705',
                'longitude' => '106.92665',
                'nama' => 'Sengon gunung/jeungjing',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Mei',
                'latitude' => '-6.83671',
                'longitude' => '106.90875',
                'nama' => 'Kicareuh',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Mei',
                'latitude' => '-6.83671',
                'longitude' => '106.90875',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Mei',
                'latitude' => '-6.715919',
                'longitude' => '106.90976',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Tegallega',
                'bulan' => 'Mei',
                'latitude' => '-6.83236663',
                'longitude' => '107.0346542',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Tegallega',
                'bulan' => 'Mei',
                'latitude' => '-6.83236663',
                'longitude' => '107.0346542',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Tegallega',
                'bulan' => 'Mei',
                'latitude' => '-6.835095',
                'longitude' => '107.042591',
                'nama' => 'Pasang',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Mei',
                'latitude' => '-6.708823',
                'longitude' => '106.99199',
                'nama' => 'Riung anak',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Mei',
                'latitude' => '-6.708657',
                'longitude' => '106.991915',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Mei',
                'latitude' => '-6.733016',
                'longitude' => '106.994147',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Mei',
                'latitude' => '-6.773539',
                'longitude' => '107.015495',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Mei',
                'latitude' => '-6.773539',
                'longitude' => '107.015495',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Mei',
                'latitude' => '-6.773547',
                'longitude' => '107.014781',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.835506',
                'longitude' => '106.926049',
                'nama' => 'Kitandu',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.835506',
                'longitude' => '106.926049',
                'nama' => 'Talingkup',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Mei',
                'latitude' => '-6.722875',
                'longitude' => '106.902197',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Mei',
                'latitude' => '-6.726265',
                'longitude' => '106.90603',
                'nama' => 'Alang-alang, jukut eurih',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Mei',
                'latitude' => '-6.732404',
                'longitude' => '106.923377',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Mei',
                'latitude' => '-6.804137',
                'longitude' => '106.922671',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Mei',
                'latitude' => '-6.825344',
                'longitude' => '106.832488',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Mei',
                'latitude' => '-6.82553',
                'longitude' => '106.835709',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Mei',
                'latitude' => '-6.821325',
                'longitude' => '106.824312',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Mei',
                'latitude' => '-6.767725',
                'longitude' => '107.001177',
                'nama' => 'Huru kawoyang',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Mei',
                'latitude' => '-6.767473',
                'longitude' => '107.001527',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Gunung Putri',
                'bulan' => 'Mei',
                'latitude' => '-6.758472',
                'longitude' => '107.000748',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Mei',
                'latitude' => '-6.845337',
                'longitude' => '106.97654',
                'nama' => 'Akar kupu-kupu, rane',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Mei',
                'latitude' => '-6.844312',
                'longitude' => '106.976704',
                'nama' => 'Harendong',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Mei',
                'latitude' => '-6.844352',
                'longitude' => '106.976503',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.832763',
                'longitude' => '106.921079',
                'nama' => 'Kikopi',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.83125',
                'longitude' => '106.932411',
                'nama' => 'Campaka leuweung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Juni',
                'latitude' => '-6.716083',
                'longitude' => '106.913109',
                'nama' => 'Kayu afrika',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.834152',
                'longitude' => '106.923793',
                'nama' => 'Kecubung',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.831346',
                'longitude' => '106.921264',
                'nama' => 'Riung anak',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.831346',
                'longitude' => '106.921264',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Juni',
                'latitude' => '-6.735271',
                'longitude' => '107.005845',
                'nama' => 'Kecubung',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Juni',
                'latitude' => '-6.738949',
                'longitude' => '107.012423',
                'nama' => 'Honje warak',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Juni',
                'latitude' => '-6.7254',
                'longitude' => '107.992482',
                'nama' => 'Loa/Kondang',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Juni',
                'latitude' => '-6.724548',
                'longitude' => '106.993315',
                'nama' => 'Riung anak',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Juni',
                'latitude' => '-6.823596',
                'longitude' => '106.816426',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Juni',
                'latitude' => '-6.822343',
                'longitude' => '106.82971',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Juni',
                'latitude' => '-6.819193',
                'longitude' => '106.826793',
                'nama' => 'Lame',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juni',
                'latitude' => '-6.846145',
                'longitude' => '106.970826',
                'nama' => 'Akar kupu-kupu, rane',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juni',
                'latitude' => '-6.845449',
                'longitude' => '106.970891',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juni',
                'latitude' => '-6.845929',
                'longitude' => '106.972174',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juni',
                'latitude' => '-6.844357',
                'longitude' => '106.972273',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Juni',
                'latitude' => '-6.836687',
                'longitude' => '106.966982',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Juni',
                'latitude' => '-6.844777',
                'longitude' => '106.962161',
                'nama' => 'Kecubung',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Juni',
                'latitude' => '-6.84213',
                'longitude' => '106.96353',
                'nama' => 'Iles-iles',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Juni',
                'latitude' => '-6.7680466',
                'longitude' => '107.024685',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Juni',
                'latitude' => '-6.7709216',
                'longitude' => '107.020923',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Juni',
                'latitude' => '-6.831428',
                'longitude' => '106.921305',
                'nama' => 'Akar kupu-kupu, rane',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Juni',
                'latitude' => '-6.725303',
                'longitude' => '106.897659',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Juni',
                'latitude' => '-6.813792',
                'longitude' => '106.903758',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Juli',
                'latitude' => '-6.740605',
                'longitude' => '106.916507',
                'nama' => 'Campaka leuweung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Juli',
                'latitude' => '-6.718183',
                'longitude' => '106.91209',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Juli',
                'latitude' => '-6.714633',
                'longitude' => '106.903775',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Juli',
                'latitude' => '-6.705815',
                'longitude' => '106.928165',
                'nama' => 'Kiara jingkang',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Juli',
                'latitude' => '-6.771147',
                'longitude' => '107.019247',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Juli',
                'latitude' => '-6.771147',
                'longitude' => '107.019247',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Juli',
                'latitude' => '-6.742595',
                'longitude' => '106.99939',
                'nama' => 'Honje warak',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Juli',
                'latitude' => '-6.727812',
                'longitude' => '106.995085',
                'nama' => 'Tongtak',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Juli',
                'latitude' => '-6.727527',
                'longitude' => '106.995883',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Bodogol',
                'bulan' => 'Juli',
                'latitude' => '-6.775345',
                'longitude' => '106.85489',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Juli',
                'latitude' => '-6.82016',
                'longitude' => '106.825806',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Juli',
                'latitude' => '-6.826243',
                'longitude' => '106.874619',
                'nama' => 'Hariang bodas',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Juli',
                'latitude' => '-6.821905',
                'longitude' => '106.835421',
                'nama' => 'Huru mentek',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.846902',
                'longitude' => '106.972117',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.846365',
                'longitude' => '106.972212',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.845686',
                'longitude' => '106.972151',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.844956',
                'longitude' => '106.972183',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.846792',
                'longitude' => '106.971703',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.845601',
                'longitude' => '106.97129',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.845275',
                'longitude' => '106.971395',
                'nama' => 'Rotan ragas/hoe leuleus/bogo',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.848525',
                'longitude' => '106.976643',
                'nama' => 'Pandan areuy',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.848168',
                'longitude' => '106.975863',
                'nama' => 'Akar kupu-kupu, rane',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Juli',
                'latitude' => '-6.844527',
                'longitude' => '106.975824',
                'nama' => 'Rotan badak/bungbuay',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Juli',
                'latitude' => '-6.840845',
                'longitude' => '106.964365',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Juli',
                'latitude' => '-6.835706',
                'longitude' => '106.959943',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Juli',
                'latitude' => '-6.843983',
                'longitude' => '106.934979',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Juli',
                'latitude' => '-6.804324',
                'longitude' => '106.921923',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Juli',
                'latitude' => '-6.734502',
                'longitude' => '107.005572',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.833638',
                'longitude' => '106.92666',
                'nama' => 'Kilemo',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.834172',
                'longitude' => '106.929625',
                'nama' => 'Huru kawoyang',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.836106',
                'longitude' => '106.928553',
                'nama' => 'Pingku',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Agustus',
                'latitude' => '-6.714136',
                'longitude' => '106.905282',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Agustus',
                'latitude' => '-6.716761',
                'longitude' => '106.906762',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Agustus',
                'latitude' => '-6.718224',
                'longitude' => '106.907543',
                'nama' => 'Rotan ragas/hoe leuleus/bogo',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.829195',
                'longitude' => '106.931722',
                'nama' => 'Iles-iles',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.833944',
                'longitude' => '106.924584',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.829078',
                'longitude' => '106.931348',
                'nama' => 'Hariang hejo',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.829185',
                'longitude' => '106.93103',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.829673',
                'longitude' => '106.930982',
                'nama' => 'Reundeu',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.828982',
                'longitude' => '106.931148',
                'nama' => 'Reundeu badak',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.828982',
                'longitude' => '106.931148',
                'nama' => 'Reundeu badak',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.829345',
                'longitude' => '106.931133',
                'nama' => 'Walen',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Agustus',
                'latitude' => '-6.829594',
                'longitude' => '106.931139',
                'nama' => 'Sembung lalaki',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Agustus',
                'latitude' => '-6.824115',
                'longitude' => '106.834629',
                'nama' => 'Salam anjing/huru',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Agustus',
                'latitude' => '-6.820164',
                'longitude' => '106.825872',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Agustus',
                'latitude' => '-6.820164',
                'longitude' => '106.825872',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.727522',
                'longitude' => '106.996162',
                'nama' => 'Kecubung',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.727812',
                'longitude' => '106.995085',
                'nama' => 'Tongtak',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.727005',
                'longitude' => '106.9966',
                'nama' => 'Areuy konyal',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.751432',
                'longitude' => '106.986493',
                'nama' => 'Hariang beureum',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.751237',
                'longitude' => '106.985917',
                'nama' => 'Honje warak.',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.750665',
                'longitude' => '106.985402',
                'nama' => 'Harendong',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Agustus',
                'latitude' => '-6.741518',
                'longitude' => '107.003245',
                'nama' => 'Pranajiwa',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Agustus',
                'latitude' => '-6.781378',
                'longitude' => '107.022568',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Agustus',
                'latitude' => '-6.781378',
                'longitude' => '107.022568',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Agustus',
                'latitude' => '-6.447',
                'longitude' => '107.03',
                'nama' => 'Cau kole/pisang hutan',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Agustus',
                'latitude' => '-6.834476',
                'longitude' => '106.989124',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'Agustus',
                'latitude' => '-6.720399',
                'longitude' => '106.940704',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Agustus',
                'latitude' => '-6.833383',
                'longitude' => '106.989317',
                'nama' => 'Beunying',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Agustus',
                'latitude' => '-6.845234',
                'longitude' => '106.977222',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Agustus',
                'latitude' => '-6.844526',
                'longitude' => '106.977165',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'September',
                'latitude' => '-6.4356',
                'longitude' => '107.013',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'September',
                'latitude' => '-6.780655',
                'longitude' => '107.003454',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'September',
                'latitude' => '-6.780655',
                'longitude' => '107.003454',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'September',
                'latitude' => '-6.780655',
                'longitude' => '107.003454',
                'nama' => 'Huru manjel/kimanjel',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'September',
                'latitude' => '-6.775496',
                'longitude' => '107.020639',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'September',
                'latitude' => '-6.773925',
                'longitude' => '107.014848',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'September',
                'latitude' => '-6.819774',
                'longitude' => '106.825498',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'September',
                'latitude' => '-6.814013',
                'longitude' => '106.843499',
                'nama' => 'Panggang serem/puyu',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'September',
                'latitude' => '-6.829602',
                'longitude' => '106.873261',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'September',
                'latitude' => '-6.747895',
                'longitude' => '106.986543',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'September',
                'latitude' => '-6.750103',
                'longitude' => '106.982393',
                'nama' => 'Honje warak.',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'September',
                'latitude' => '-6.748962',
                'longitude' => '106.981502',
                'nama' => 'Harendong',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'September',
                'latitude' => '-6.721933',
                'longitude' => '106.92626',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'September',
                'latitude' => '-6.725362',
                'longitude' => '106.924405',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'September',
                'latitude' => '-6.695777',
                'longitude' => '106.922451',
                'nama' => 'Janitri',
            ],
            [
                'resort' => 'Cisarua',
                'bulan' => 'September',
                'latitude' => '-6.7259',
                'longitude' => '106.936952',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'September',
                'latitude' => '-6.727262',
                'longitude' => '106.906295',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'September',
                'latitude' => '-6.730097',
                'longitude' => '106.907838',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'September',
                'latitude' => '-6.841578',
                'longitude' => '106.936057',
                'nama' => 'Kicareuh',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'September',
                'latitude' => '-6.831811',
                'longitude' => '106.927087',
                'nama' => 'Campaka leuweung',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'September',
                'latitude' => '-6.829697',
                'longitude' => '106.926891',
                'nama' => 'Rotan ragas/hoe leuleus/bogo',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'September',
                'latitude' => '-6.829528',
                'longitude' => '106.92688',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'September',
                'latitude' => '-6.829288',
                'longitude' => '106.926459',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'September',
                'latitude' => '-6.828832',
                'longitude' => '106.925439',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'September',
                'latitude' => '-6.846651',
                'longitude' => '106.970775',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'September',
                'latitude' => '-6.845523',
                'longitude' => '106.971263',
                'nama' => 'Paku sarang burung',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'September',
                'latitude' => '-6.836361',
                'longitude' => '106.996139',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'September',
                'latitude' => '-6.836256',
                'longitude' => '106.989407',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.836137',
                'longitude' => '106.926813',
                'nama' => 'Bingbin',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Oktober',
                'latitude' => '-6.733344',
                'longitude' => '106.917614',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Oktober',
                'latitude' => '-6.741855',
                'longitude' => '106.921367',
                'nama' => 'Kicareuh',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Oktober',
                'latitude' => '-6.74312',
                'longitude' => '106.922574',
                'nama' => 'Bunga Bangkai',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Oktober',
                'latitude' => '-6.741763',
                'longitude' => '106.921729',
                'nama' => 'Lampeni',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.82079',
                'longitude' => '106.947144',
                'nama' => 'Pacar tere',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.82113',
                'longitude' => '106.947405',
                'nama' => 'Pingku',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.821764',
                'longitude' => '106.946642',
                'nama' => 'Loa/Kondang',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.821634',
                'longitude' => '106.946886',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.82156',
                'longitude' => '106.947007',
                'nama' => 'Acung',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.821184',
                'longitude' => '106.946926',
                'nama' => 'Kayu getah ajag',
            ],
            [
                'resort' => 'Situgunung',
                'bulan' => 'Oktober',
                'latitude' => '-6.82095',
                'longitude' => '106.946888',
                'nama' => 'Iles-iles',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Oktober',
                'latitude' => '-6.815607',
                'longitude' => '106.91679',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Oktober',
                'latitude' => '-6.822598',
                'longitude' => '106.913483',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Oktober',
                'latitude' => '-6.751063',
                'longitude' => '106.988782',
                'nama' => 'Kihujan',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Oktober',
                'latitude' => '-6.740089',
                'longitude' => '107.002709',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Oktober',
                'latitude' => '-6.824129',
                'longitude' => '106.834581',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Oktober',
                'latitude' => '-6.818365',
                'longitude' => '106.843844',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Oktober',
                'latitude' => '-6.819577',
                'longitude' => '106.828668',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Oktober',
                'latitude' => '-6.77198',
                'longitude' => '107.015295',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Oktober',
                'latitude' => '-6.77198',
                'longitude' => '107.015295',
                'nama' => 'Huru madang/koneng',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Oktober',
                'latitude' => '-6.4356',
                'longitude' => '107.013',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Oktober',
                'latitude' => '-6.841986',
                'longitude' => '106.984048',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Oktober',
                'latitude' => '-6.840179',
                'longitude' => '106.990514',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Nopember',
                'latitude' => '-6.841986',
                'longitude' => '106.96266',
                'nama' => 'Kileho beureum',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Nopember',
                'latitude' => '-6.841212',
                'longitude' => '106.96425',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Selabintana',
                'bulan' => 'Nopember',
                'latitude' => '-6.842034',
                'longitude' => '106.963776',
                'nama' => 'Babadotan',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Nopember',
                'latitude' => '-6.728187',
                'longitude' => '106.901438',
                'nama' => 'Tepus sigung',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Nopember',
                'latitude' => '-6.70965',
                'longitude' => '106.907316',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Nopember',
                'latitude' => '-6.721088',
                'longitude' => '106.889268',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Nopember',
                'latitude' => '-6.72681',
                'longitude' => '106.90622',
                'nama' => 'Alang-alang, jukut eurih',
            ],
            [
                'resort' => 'Tapos',
                'bulan' => 'Nopember',
                'latitude' => '-6.726449',
                'longitude' => '106.906369',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Nopember',
                'latitude' => '-6.44202',
                'longitude' => '107.0178',
                'nama' => 'Medang lesah/huru pedes',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Nopember',
                'latitude' => '-6.822305',
                'longitude' => '106.822276',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Nopember',
                'latitude' => '-6.825628',
                'longitude' => '106.834662',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Nagrak',
                'bulan' => 'Nopember',
                'latitude' => '-6.820575',
                'longitude' => '106.838818',
                'nama' => 'Reundeu',
            ],
            [
                'resort' => 'Tegallega',
                'bulan' => 'Nopember',
                'latitude' => '-6.835538',
                'longitude' => '107.016217',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cimungkad',
                'bulan' => 'Nopember',
                'latitude' => '-6.822212',
                'longitude' => '106.898162',
                'nama' => 'Saninten',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Nopember',
                'latitude' => '-6.718967',
                'longitude' => '106.99269',
                'nama' => 'Lame',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Nopember',
                'latitude' => '-6.75017',
                'longitude' => '106.989175',
                'nama' => 'Baros',
            ],
            [
                'resort' => 'Cibodas',
                'bulan' => 'Nopember',
                'latitude' => '-6.746153',
                'longitude' => '106.996987',
                'nama' => 'Loa/Kondang',
            ],
            [
                'resort' => 'Mandalawangi',
                'bulan' => 'Nopember',
                'latitude' => '-6.44217',
                'longitude' => '107.0002',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Pasirhantap',
                'bulan' => 'Nopember',
                'latitude' => '-6.802388',
                'longitude' => '106.818175',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Nopember',
                'latitude' => '-6.770058',
                'longitude' => '107.015079',
                'nama' => 'Puspa',
            ],
            [
                'resort' => 'Sarongge',
                'bulan' => 'Nopember',
                'latitude' => '-6.770058',
                'longitude' => '107.015079',
                'nama' => 'Rasamala',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Nopember',
                'latitude' => '-6.842655',
                'longitude' => '106.984353',
                'nama' => 'Janitri leutik',
            ],
            [
                'resort' => 'Goalpara',
                'bulan' => 'Nopember',
                'latitude' => '-6.841662',
                'longitude' => '106.984397',
                'nama' => 'Harendong bulu, harendong lalaki',
            ],
        ];

        // Loop melalui data dan masukkan ke dalam tabel menggunakan model Tumbuhan
        foreach ($data as $tumbuhanData) {
            Tumbuhan::create($tumbuhanData);
        }
    }
}
